
server:
  port: 7888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: zuul

zuul:
  routes:
    provider2: /abc/**

