spring:
  application:
    name: provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
server:
  port: 8077
  management:
    endpoints:
      web:
        exposure:
          include: hystrix.stream
