server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenXiaYu/spring-configs
  application:
    name: springConfigServer
#  security:
#    user:
#      name: user
#      password: user
management:
  endpoints:
    web:
      exposure:
        include: refresh
